export const statesInIndia = [
    { name: 'Andhra Pradesh, India', value: 'Andhra Pradesh' },
    { name: 'Arunachal Pradesh, India', value: 'Arunachal Pradesh' },
    { name: 'Assam, India', value: 'Assam' },
    { name: 'Bihar, India', value: 'Bihar' },
    { name: 'Chhattisgarh, India', value: 'Chhattisgarh' },
    { name: 'Goa, India', value: 'Goa' },
    { name: 'Gujarat, India', value: 'Gujarat' },
    { name: 'Haryana, India', value: 'Haryana' },
    { name: 'Himachal Pradesh, India', value: 'Himachal Pradesh' },
    { name: 'Jharkhand, India', value: 'Jharkhand' },
    { name: 'Karnataka, India', value: 'Karnataka' },
    { name: 'Kerala, India', value: 'Kerala' },
    { name: 'Madhya Pradesh, India', value: 'Madhya Pradesh' },
    { name: 'Maharashtra, India', value: 'Maharashtra' },
    { name: 'Manipur, India', value: 'Manipur' },
    { name: 'Meghalaya, India', value: 'Meghalaya' },
    { name: 'Mizoram, India', value: 'Mizoram' },
    { name: 'Nagaland, India', value: 'Nagaland' },
    { name: 'Odisha, India', value: 'Odisha' },
    { name: 'Punjab, India', value: 'Punjab' },
    { name: 'Rajasthan, India', value: 'Rajasthan' },
    { name: 'Sikkim, India', value: 'Sikkim' },
    { name: 'Tamil Nadu, India', value: 'Tamil Nadu' },
    { name: 'Telangana, India', value: 'Telangana' },
    { name: 'Tripura, India', value: 'Tripura' },
    { name: 'Uttar Pradesh, India', value: 'Uttar Pradesh' },
    { name: 'Uttarakhand, India', value: 'Uttarakhand' },
    { name: 'West Bengal, India', value: 'West Bengal' },
  ];
  